//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.16 at 12:01:56 PM CEST 
//


package allapis.praksa.com.user;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the allapis.praksa.com.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: allapis.praksa.com.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertUserRequest }
     * 
     */
    public InsertUserRequest createInsertUserRequest() {
        return new InsertUserRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link InsertUserResponse }
     * 
     */
    public InsertUserResponse createInsertUserResponse() {
        return new InsertUserResponse();
    }

    /**
     * Create an instance of {@link RetrieveUserByEmailRequest }
     * 
     */
    public RetrieveUserByEmailRequest createRetrieveUserByEmailRequest() {
        return new RetrieveUserByEmailRequest();
    }

    /**
     * Create an instance of {@link RetrieveUserByEmailResponse }
     * 
     */
    public RetrieveUserByEmailResponse createRetrieveUserByEmailResponse() {
        return new RetrieveUserByEmailResponse();
    }

}
